app.discord.token=${DISCORD_TOKEN}
app.youtube.potoken=${YOUTUBE_POTOKEN}
app.youtube.visitor=${YOUTUBE_VISITOR}
app.youtube.oauth2=${YOUTUBE_OAUTH2}
app.spotify.clientId=${SPOTIFY_CLIENT_ID}
app.spotify.clientSecret=${SPOTIFY_CLIENT_SECRET}
app.music.max-pending-loads=20
app.music.max-queue-size=500
app.music.max-playlist-tracks=100
